[project]
name = "lean-client"
version = "0.0.1.dev1"
description = "A Python client for the Lean Server API."
readme = "README.md"
requires-python = ">=3.12"
authors = [
    { name = "Pu Fanyi", email = "FPU001@e.ntu.edu.sg" },
]
keywords = ["lean-client", "lean-server"]
dependencies = [
    "aiohttp>=3.9.0",
    "pydantic>=2.0.0"
]

[project.urls]
repository = "https://github.com/pufanyi/lean-server"

[tool.setuptools.packages.find]
include = ["client*"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
