lean:
  executable: /home/fypu/.elan/bin/lake
  workspace: /root/lmms-lean-runner/playground
sqlite:
  database_path: /root/lmms-lean-runner/lean_server.db
  timeout: 10
logging:
  version: 1
  disable_existing_loggers: false
  handlers:
    default:
      class: "rich.logging.RichHandler"
      level: "INFO"
      rich_tracebacks: true
      tracebacks_word_wrap: false
  loggers:
    lean_server:
      handlers:
        - "default"
      level: "INFO"
    uvicorn:
      handlers:
        - "default"
      level: "INFO"
      propagate: false
    uvicorn.error:
      handlers:
        - "default"
      level: "INFO"
      propagate: false
    uvicorn.access:
      handlers:
        - "default"
      level: "INFO"
      propagate: false
