lean:
  # executable: /root/.elan/bin/lake
  # workspace: /root/playground
  executable: /home/libo/.elan/bin/lake
  workspace: /mnt/raid10/pufanyi/prover/playground
sqlite:
  database_path: /mnt/raid10/pufanyi/prover/lean_server.db
  timeout: 10
logging:
  version: 1
  disable_existing_loggers: false
  handlers:
    default:
      class: "rich.logging.RichHandler"
      level: "INFO"
      rich_tracebacks: true
      tracebacks_word_wrap: false
  loggers:
    uvicorn:
      handlers:
        - "default"
      level: "INFO"
      propagate: false
    uvicorn.error:
      handlers:
        - "default"
      level: "INFO"
      propagate: false
    uvicorn.access:
      handlers:
        - "default"
      level: "INFO"
      propagate: false
