version: '3.8'

services:
  lean-server:
    build: .
    image: lmms-lean-runner-image
    container_name: lmms-lean-runner
    ports:
      - "${LEAN_SERVER_PORT:-8000}:8000"
    restart: unless-stopped
