# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: prove.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "prove.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0bprove.proto\x12\x0blean_runner\x1a\x1cgoogle/protobuf/struct.proto"K\n\x11\x43heckProofRequest\x12\r\n\x05proof\x18\x01 \x01(\t\x12\'\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct"L\n\x12SubmitProofRequest\x12\r\n\x05proof\x18\x01 \x01(\t\x12\'\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct"\'\n\x13SubmitProofResponse\x12\x10\n\x08proof_id\x18\x01 \x01(\t"$\n\x10GetResultRequest\x12\x10\n\x08proof_id\x18\x01 \x01(\t"W\n\x0bProofResult\x12\x10\n\x08proof_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0e\n\x06result\x18\x03 \x01(\t\x12\x15\n\rerror_message\x18\x04 \x01(\t2\xee\x01\n\x0cProveService\x12\x46\n\nCheckProof\x12\x1e.lean_runner.CheckProofRequest\x1a\x18.lean_runner.ProofResult\x12P\n\x0bSubmitProof\x12\x1f.lean_runner.SubmitProofRequest\x1a .lean_runner.SubmitProofResponse\x12\x44\n\tGetResult\x12\x1d.lean_runner.GetResultRequest\x1a\x18.lean_runner.ProofResultBCZAgithub.com/EvolvingLMMs-Lab/lean-runner/server/gen/go/lean_runnerb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "prove_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = (
        b"ZAgithub.com/EvolvingLMMs-Lab/lean-runner/server/gen/go/lean_runner"
    )
    _globals["_CHECKPROOFREQUEST"]._serialized_start = 58
    _globals["_CHECKPROOFREQUEST"]._serialized_end = 133
    _globals["_SUBMITPROOFREQUEST"]._serialized_start = 135
    _globals["_SUBMITPROOFREQUEST"]._serialized_end = 211
    _globals["_SUBMITPROOFRESPONSE"]._serialized_start = 213
    _globals["_SUBMITPROOFRESPONSE"]._serialized_end = 252
    _globals["_GETRESULTREQUEST"]._serialized_start = 254
    _globals["_GETRESULTREQUEST"]._serialized_end = 290
    _globals["_PROOFRESULT"]._serialized_start = 292
    _globals["_PROOFRESULT"]._serialized_end = 379
    _globals["_PROVESERVICE"]._serialized_start = 382
    _globals["_PROVESERVICE"]._serialized_end = 620
# @@protoc_insertion_point(module_scope)
