name: docs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - run: uv sync --dev
      - name: Generate Sphinx RST files
        run: |
          set -x
          # Client
          uv run sphinx-apidoc -o sphinx_docs/client/source -f packages/client/lean_runner
          sed -i '/Module contents/,$d' sphinx_docs/client/source/lean_runner.rst
          sed -i '/Module contents/,$d' sphinx_docs/client/source/lean_runner.proof.rst
          rm -f sphinx_docs/client/source/modules.rst

          # Server
          uv run sphinx-apidoc -o sphinx_docs/server/source -f packages/server/lean_server
          sed -i '/Module contents/,$d' sphinx_docs/server/source/lean_server.rst
          rm -f sphinx_docs/server/source/modules.rst
      - name: Build MkDocs and Sphinx
        run: |
          uv run mkdocs build
          (cd sphinx_docs/client/source && uv run sphinx-build -b dirhtml . ../../../site/dev/docs/client)
          (cd sphinx_docs/server/source && uv run sphinx-build -b dirhtml . ../../../site/dev/docs/server)
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
